name: Android CD

on:
  push:
    branches: main
    
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Build with Gradle
      run: bash ./gradlew assembleDebug
 
    - name: change file name
      run: mv app/build/outputs/apk/dev/debug/app-dev-debug.apk app/build/outputs/apk/dev/debug/230948.apk
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: upload apk
        path: app/build/outputs/apk/dev/debug/1235151.apk
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: android-build
        SLACK_COLOR: '#DD0000'
        SLACK_ICON: https://scontent-gmp1-1.xx.fbcdn.net/v/t1.0-1/p320x320/91169376_156983249102340_1282099367657865216_n.png?_nc_cat=107&_nc_sid=1eb0c7&_nc_ohc=HUqFwEXCh1AAX9albM-&_nc_ht=scontent-gmp1-1.xx&oh=7995cc28944e6dedf4f6cf36c1649a46&oe=5F8FEB24
        SLACK_MESSAGE: '1444 개발 빌드가 완료되었습니다'
        SLACK_TITLE: '55252  개발버전 입니다.'
        SLACK_USERNAME: 개발 개발
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_FOOTER: 개발버전 입니다.
       
#     - name: 테스트용 apk artifact 업로드
#       uses: actions/upload-artifact@v2
#       with:
#         name: app-debug-unsigned.apk
#         path: app/build/outputs/apk/debug/app-debug-unsigned.apk
        
#     - name: action-slack
#       uses: 8398a7/action-slack@v3.12.0
#       with:
#         status: ${{ job.status }}
#         author_name: 빌드 알림
#       env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}    
