name: Android CD

on:
  push:
    branches: main
    
  pull_request:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
       
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
     
    - name: Build APK
      run: bash ./gradlew assembleRelease --stacktrace
     
     
    - run: './gradlew assembleRelease'
    
    - name: 테스트용 apk artifact 업로드
      uses: actions/upload-artifact@v2
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: action-slack
      uses: 8398a7/action-slack@v3.12.0
      with:
        status: ${{ job.status }}
        author_name: 빌드 알림
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  
         
    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        channel: eddy-github

