name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build
#     - name: Upload APK
#       uses: actions/upload-artifact@v2
#       with:
#         name: app-debug.apk
#         path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Build APK
      run: bash ./gradlew assembleRelease --stacktrace
     
     
    - run: './gradlew assembleRelease'
    - uses: MeilCli/slack-upload-file@v1
      with:
        slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
        file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
        file_name: 'app-release-unsigned.apk'
        file_type: 'apk'
        initial_comment: '${{ github.ref }} 테스트 앱 슬랙 배포 성공'
