name: Android CD

on:
  push:
    branches: main
    
  pull_request:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
       
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
     
    - name: Build APK
      run: bash ./gradlew assembleRelease --stacktrace
           
    - name: 테스트용 apk artifact 업로드
      uses: actions/upload-artifact@v2
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
    
    - run:
          name: Upload to Slack
          command: |
            curl -F file=@android/app/build/outputs/apk/release/app-release-unsigned.apk -F channels=TestApp -F token=${{ secrets.SLACK_READ_WRITE_TOKEN }} -F title="Here is new TIA relase build apk file"  https://slack.com/api/files.upload

